### ISSUE TITLE
How to use useUnmountBrightness 

### ISSUE THREAD

**Issue by rayhk6** [reeq-dev/react-native-device-brightness#1]
I have no idea how to use the useUnmountBrightness hook with param. Could you please add to example folder? Thanks.

**Comment by reeq-dev** [comment]
Example folder updated. Make sure you launch on real device (simulator wont change brightness):
https://github.com/reeq-dev/react-native-device-brightness/blob/2946dc6ffddb368a6ea9bc0df03efffc88ad8481/example/src/App.tsx
